export default {
	login: "Abenaesha",
	id: 77442379,
	node_id: "MDQ6VXNlcjc3NDQyMzc5",
	avatar_url: "https://avatars3.githubusercontent.com/u/77442379?v=4",
	gravatar_id: "",
	url: "https://api.github.com/users/Abenaesha",
	html_url: "https://github.com/Abenaesha",
	followers_url: "https://api.github.com/users/Abenaesha/followers",
	following_url:
		"https://api.github.com/users/Abenaesha/following{/other_user}",
	gists_url: "https://api.github.com/users/Abenaesha/gists{/gist_id}",
	starred_url: "https://api.github.com/users/Abenaesha/starred{/owner}{/repo}",
	subscriptions_url: "https://api.github.com/users/Abenaesha/subscriptions",
	organizations_url: "https://api.github.com/users/Abenaesha/orgs",
	repos_url: "https://api.github.com/users/Abenaesha/repos",
	events_url: "https://api.github.com/users/Abenaesha/events{/privacy}",
	received_events_url: "https://api.github.com/users/Abenaesha/received_events",
	type: "User",
	site_admin: false,
	name: "Abdalraof Benaesha",
	company: "Northcoders",
	blog: "https://abenaesha.github.io/",
	location: "Manchester, UK",
	email: null,
	hireable: true,
	bio: "Never settle coding! \r\nTrainee Full-Stack Dev ",
	twitter_username: "benaesha",
	public_repos: 19,
	public_gists: 0,
	followers: 7,
	following: 11,
	created_at: "2021-01-14T11:58:48Z",
	updated_at: "2021-05-05T11:30:24Z",
}
