export default [
	{
		avatar_url: "https://avatars.githubusercontent.com/u/65741990?v=4",
		events_url: "https://api.github.com/users/raflors/events{/privacy}",
		followers_url: "https://api.github.com/users/raflors/followers",
		following_url:
			"https://api.github.com/users/raflors/following{/other_user}",
		gists_url: "https://api.github.com/users/raflors/gists{/gist_id}",
		gravatar_id: "",
		html_url: "https://github.com/raflors",
		id: 65741990,
		login: "raflors",
		node_id: "MDQ6VXNlcjY1NzQxOTkw",
		organizations_url: "https://api.github.com/users/raflors/orgs",
		received_events_url: "https://api.github.com/users/raflors/received_events",
		repos_url: "https://api.github.com/users/raflors/repos",
		site_admin: false,
		starred_url: "https://api.github.com/users/raflors/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/raflors/subscriptions",
		type: "User",
		url: "https://api.github.com/users/raflors",
	},
	{
		avatar_url: "https://avatars.githubusercontent.com/u/54909909?v=4",
		events_url: "https://api.github.com/users/Jonas1220/events{/privacy}",
		followers_url: "https://api.github.com/users/Jonas1220/followers",
		following_url:
			"https://api.github.com/users/Jonas1220/following{/other_user}",
		gists_url: "https://api.github.com/users/Jonas1220/gists{/gist_id}",
		gravatar_id: "",
		html_url: "https://github.com/Jonas1220",
		id: 54909909,
		login: "Jonas1220",
		node_id: "MDQ6VXNlcjU0OTA5OTA5",
		organizations_url: "https://api.github.com/users/Jonas1220/orgs",
		received_events_url:
			"https://api.github.com/users/Jonas1220/received_events",
		repos_url: "https://api.github.com/users/Jonas1220/repos",
		site_admin: false,
		starred_url:
			"https://api.github.com/users/Jonas1220/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/Jonas1220/subscriptions",
		type: "User",
		url: "https://api.github.com/users/Jonas1220",
	},
	{
		avatar_url: "https://avatars.githubusercontent.com/u/62888461?v=4",
		events_url: "https://api.github.com/users/izuku152/events{/privacy}",
		followers_url: "https://api.github.com/users/izuku152/followers",
		following_url:
			"https://api.github.com/users/izuku152/following{/other_user}",
		gists_url: "https://api.github.com/users/izuku152/gists{/gist_id}",
		gravatar_id: "",
		html_url: "https://github.com/izuku152",
		id: 62888461,
		login: "izuku152",
		node_id: "MDQ6VXNlcjYyODg4NDYx",
		organizations_url: "https://api.github.com/users/izuku152/orgs",
		received_events_url:
			"https://api.github.com/users/izuku152/received_events",
		repos_url: "https://api.github.com/users/izuku152/repos",
		site_admin: false,
		starred_url: "https://api.github.com/users/izuku152/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/izuku152/subscriptions",
		type: "User",
		url: "https://api.github.com/users/izuku152",
	},
	{
		avatar_url: "https://avatars.githubusercontent.com/u/73906265?v=4",
		events_url: "https://api.github.com/users/wei-yiting/events{/privacy}",
		followers_url: "https://api.github.com/users/wei-yiting/followers",
		following_url:
			"https://api.github.com/users/wei-yiting/following{/other_user}",
		gists_url: "https://api.github.com/users/wei-yiting/gists{/gist_id}",
		gravatar_id: "",
		html_url: "https://github.com/wei-yiting",
		id: 73906265,
		login: "wei-yiting",
		node_id: "MDQ6VXNlcjczOTA2MjY1",
		organizations_url: "https://api.github.com/users/wei-yiting/orgs",
		received_events_url:
			"https://api.github.com/users/wei-yiting/received_events",
		repos_url: "https://api.github.com/users/wei-yiting/repos",
		site_admin: false,
		starred_url:
			"https://api.github.com/users/wei-yiting/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/wei-yiting/subscriptions",
		type: "User",
		url: "https://api.github.com/users/wei-yiting",
	},
	{
		avatar_url: "https://avatars.githubusercontent.com/u/61985589?v=4",
		events_url: "https://api.github.com/users/jonjonbenben/events{/privacy}",
		followers_url: "https://api.github.com/users/jonjonbenben/followers",
		following_url:
			"https://api.github.com/users/jonjonbenben/following{/other_user}",
		gists_url: "https://api.github.com/users/jonjonbenben/gists{/gist_id}",
		gravatar_id: "",
		html_url: "https://github.com/jonjonbenben",
		id: 61985589,
		login: "jonjonbenben",
		node_id: "MDQ6VXNlcjYxOTg1NTg5",
		organizations_url: "https://api.github.com/users/jonjonbenben/orgs",
		received_events_url:
			"https://api.github.com/users/jonjonbenben/received_events",
		repos_url: "https://api.github.com/users/jonjonbenben/repos",
		site_admin: false,
		starred_url:
			"https://api.github.com/users/jonjonbenben/starred{/owner}{/repo}",
		subscriptions_url:
			"https://api.github.com/users/jonjonbenben/subscriptions",
		type: "User",
		url: "https://api.github.com/users/jonjonbenben",
	},
	{
		avatar_url: "https://avatars.githubusercontent.com/u/76622730?v=4",
		events_url: "https://api.github.com/users/DCrawley94/events{/privacy}",
		followers_url: "https://api.github.com/users/DCrawley94/followers",
		following_url:
			"https://api.github.com/users/DCrawley94/following{/other_user}",
		gists_url: "https://api.github.com/users/DCrawley94/gists{/gist_id}",
		gravatar_id: "",
		html_url: "https://github.com/DCrawley94",
		id: 76622730,
		login: "DCrawley94",
		node_id: "MDQ6VXNlcjc2NjIyNzMw",
		organizations_url: "https://api.github.com/users/DCrawley94/orgs",
		received_events_url:
			"https://api.github.com/users/DCrawley94/received_events",
		repos_url: "https://api.github.com/users/DCrawley94/repos",
		site_admin: false,
		starred_url:
			"https://api.github.com/users/DCrawley94/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/DCrawley94/subscriptions",
		type: "User",
		url: "https://api.github.com/users/DCrawley94",
	},
	{
		avatar_url: "https://avatars.githubusercontent.com/u/66171263?v=4",
		events_url: "https://api.github.com/users/lukerspace/events{/privacy}",
		followers_url: "https://api.github.com/users/lukerspace/followers",
		following_url:
			"https://api.github.com/users/lukerspace/following{/other_user}",
		gists_url: "https://api.github.com/users/lukerspace/gists{/gist_id}",
		gravatar_id: "",
		html_url: "https://github.com/lukerspace",
		id: 66171263,
		login: "lukerspace",
		node_id: "MDQ6VXNlcjY2MTcxMjYz",
		organizations_url: "https://api.github.com/users/lukerspace/orgs",
		received_events_url:
			"https://api.github.com/users/lukerspace/received_events",
		repos_url: "https://api.github.com/users/lukerspace/repos",
		site_admin: false,
		starred_url:
			"https://api.github.com/users/lukerspace/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/lukerspace/subscriptions",
		type: "User",
		url: "https://api.github.com/users/lukerspace",
	},
]
